Datasets:
  Full:
    Location: "/ivi/ilps/personal/pkhande/"
    UseLocalFiles: False
    Normalization: True
    NormalizationType: "Query"
    FilterQueries: True
    fold: 1
    ID: "MSLR30K"
    Sample: ''  # Sampling the original dataset query wise
    ExpSample: False
    ExpSampleType: "BigQueries"
    ExpSampleBug: 0.05
    SampledQuerySize: 1
    Bsz: 48
    Thr: 300
  Distilled:
    SampleQueryWise: True
    SampleDocWise: False
    CompressionRatio: 0.01
    QuerySize: 0
    RandInit: True
    Bsz: 16
    ExplicitRelLabels: -1 # If < 0 not enabled, should be up to max rel labels for the original dataset
    RandomSelectionBudget: -1 # If > 0, select this number of docs per label, otherwise, there would be only mean vector
  Sampled:
    SamplingMethod: "BigQueries"
    SamplingBudget: 0.1
    SamplingQueryBudget: 50

Trainer:
  GMEpochs: 10
  Epochs: 20
  ModelInstances: 500
  BatchSize: 256
  Suffle: False
  RankingLoss: LambdaNDCGLoss2
  DistillLoss: MSEGRADIENTMATCHLOSS
  Optimizer: ADAM
  DistillLR: 0.01
  RankingLR: 0.1
  RP: 0.8 # I think this should be removed
  BothDatasetsFullBatch: False # I think this should be removed
  ModelType: "MLP"
  ModelScale: 1
  MultiBatchDistilledData: False
  LabelWiseDistillation: False

General:
  Device: "cuda"
  SaveDistilledModelPath: "best_distilled.pt"
  Deterministic: True
  Seed: 27
  Runs: 5
  Wandb: True
  Alg: "GM"
  SaveDir: "/ivi/ilps/personal/pkhande/sigir-rep-2024/distillation/"
  ValidFreq: 5
  ValidPatience: 25
  ValidFreqInstance: 1
  ValidPatienceInstance: 2
  SamplingExp: False
  ClickExp: False

Experiment:
  Name: "gm_sample_queries_lambda_loss"
  CodeTag: "v0.4.6_et"
